# inherit_from: .rubocop_todo.yml
require:
  - rubocop-rake
  - rubocop-rspec
AllCops:
  NewCops: enable
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/*.rake'
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 100
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  ()
    '%q': ()
    '%Q': ()
    '%i': []
    '%I': []
    '%r': ()
    '%s': ()
    '%w': []
    '%W': []
    '%x': ()
