language: ruby
cache: bundler
rvm:
  - 2.2.5
  - 2.3.1
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
addons:
  code_climate:
    repo_token: f69bb189f348c1d7992d8ed8690d0a2c9c885c1aac45e2f4d48732034592b37b
services:
  - redis-server
env:
  global:
    - REDIS_URL=redis://localhost:6379
notifications:
  email: false
