language: ruby
rvm:
  - 2.2.1
  - ruby-head
addons:
  code_climate:
    repo_token: f337d3f4f1e22f0eda159e18852b13cdaca525459ce94284e0c4b33cce02d888
services:
  - redis-server
env:
  global:
    - REDIS_URL=redis://localhost:6379
